reload-message: "&a&lReloaded Tescoland!"
no-permission: "&cYou do not have permission to use this command"

map:
  message: "&7Click this link to view the web-map: "
  link: "https://bit.ly/3isE28m"
  link-text: "&bhttps://bit.ly/3isE28m"
  hover: "&6Click Me!"
