reload-message: "&a&lReloaded Tescoland!"
no-permission: "&cYou do not have permission to use this command"

3dmap:
  message: "&7Click this link to view the 3D web-map: "
  link: "https://bit.ly/3e8FkC5"
  link-text: "&bhttps://bit.ly/3e8FkC5"
  hover: "&6Click Me!"
2dmap:
  message: "&7Click this link to view the 2D web-map: "
  link: "https://bit.ly/3isE28m"
  link-text: "&bhttps://bit.ly/3isE28m"
  hover: "&6Click Me!"
