reload-message: "&a&lReloaded Fatherland!"
no-permission: "&cYou do not have permission to use this command"

slowmap:
  message: "&7Click this link to view the slow 3D web-map: "
  link: "https://bit.ly/3e8FkC5"
  link-text: "&bhttps://bit.ly/3e8FkC5"
  hover: "&6Click Me!"
fastmap:
  message: "&7Click this link to view the fast 2D web-map: "
  link: "https://bit.ly/3isE28m"
  link-text: "&bhttps://bit.ly/3isE28m"
  hover: "&6Click Me!"
