reload-message: "&a&lReloaded Tescoland!"
no-permission: "&cYou do not have permission to use this command"

map:
  message: "&7Click this link to view the web-map: "
  link: "https://bit.ly/3hMIHB4"
  link-text: "&bhttps://bit.ly/3hMIHB4"
  hover: "&6Click Me!"
discord:
  message: "&7Join our discord server at: "
  link: "https://bit.ly/3dfamIk"
  link-text: "&bhttps://bit.ly/3dfamIk"
  hover: "&6Click Me!"
