name: Fatherland
version: ${project.version}
main: me.poongwin.fatherland.Fatherland
api-version: 1.17
authors: [ poongwin ]
description: Main plugin of the Fatherland server!
commands:
  map:
    description: Gives the links to both 3D and 2D maps.
    usage: /<command>
  fatherland:
    description: The main Fatherland command.
    usage: /<command>