name: Tescoland
version: ${project.version}
main: com.poongwin.tescoland.Tescoland
api-version: 1.17
authors: [ poongwin ]
description: The official plugin of the Tescoland server.
website: https://discord.gg/sZd9gAXKZb
commands:
  map:
    description: Gives the links to both 3D and 2D maps.
    usage: /<command>
  tescoland:
    description: The main Tescoland command.
    usage: /<command>